### ISSUE TITLE
Password to see old website

### ISSUE THREAD

**Issue by sergiolopezgit** [Fijxu/BooyahDocs#8]
Hey, whats the password to the see old websites? by the way im looking for a route to get all current users in chatroom.

**Comment by sergiolopezgit** [comment]
https://booyah.live/api/v3/chatrooms/<chatroom_id>/audiences?cursor=0&count=100000

**Comment by Fijxu** [comment]
The password is `1337`, and what you just put there works fine, it takes all logged in users watching the stream so it will work for you
